name: "Course Schedule Updates"
on:
  - pull_request

jobs:
  course-schedule:
    runs-on: ubuntu-latest
    name: Update Course Schedule
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust cache
        uses: ./.github/workflows/setup-rust-cache

      - name: Generate Schedule
        run: cargo run -p mdbook-course --bin course-schedule > course-schedule.md

      - name: Upload Schedule as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: course-schedule
          path: course-schedule.md
          if-no-files-found: error
          retention-days: 1

